{% set name = "seekpath" %}
{% set version = "2.1.0" %}
{% set sha256 = "31cec579628262e6d4a4c3693fefa70d6ccae1ceeef7c9d10ea3cd48988452c4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - numpy >=1.0
    - spglib >=1.9.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - seekpath
    - seekpath.brillouinzone
    - seekpath.hpkot

about:
  home: http://github.com/giovannipizzi/seekpath
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: A module to obtain and visualize k-vector coefficients and obtain band paths in the Brillouin zone of crystal structures.

extra:
  recipe-maintainers:
    - npavlovikj
    - jan-janssen
