{% set name = "seekpath" %}
{% set version = "1.9.5" %}
{% set sha256 = "55fdd5a84015233bf92eee459af44d11f0f6f85cd936730f95b46642805c93b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - future >=0.15
    - numpy >=1.0
    - spglib >=1.9.4

test:
  imports:
    - seekpath
    - seekpath.brillouinzone
    - seekpath.hpkot

about:
  home: http://github.com/giovannipizzi/seekpath
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE.txt
  summary: A module to obtain and visualize k-vector coefficients and obtain band paths in the Brillouin zone of crystal structures.

extra:
  recipe-maintainers:
    - npavlovikj
    - jan-janssen
