schema_version: 1

context:
  name: seekpath
  version: "2.2.2"
  sha256: d3bb08b7fb21d5cff5fc27aff9904a865da5e0648fc0f8fef699642d88e27f2b

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - flit-core >=3.4,<4
  run:
    - python >=${{ python_min }}
    - numpy >=1.0
    - packaging
    - spglib >=1.14.1
    - scipy >=1

tests:
  - python:
      imports:
        - seekpath
        - seekpath.brillouinzone
        - seekpath.hpkot
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - python -c "import seekpath; seekpath.get_path(([[1, 0, 0], [0, 1, 0], [0, 0, 1]], [[0, 0, 0]], [1]))"
      - python -c "import seekpath; seekpath.get_explicit_k_path(([[1, 0, 0], [0, 1, 0], [0, 0, 1]], [[0, 0, 0]], [1]))"
about:
  license: MIT
  license_file: LICENSE.txt
  summary: A module to obtain and visualize k-vector coefficients and obtain band paths in the Brillouin zone of crystal structures.
  homepage: https://github.com/materialscloud-org/seekpath

extra:
  recipe-maintainers:
    - t-reents
    - npavlovikj
    - jan-janssen
