schema_version: 1

context:
  name: seekpath
  version: "2.2.2"
  sha256: d3bb08b7fb21d5cff5fc27aff9904a865da5e0648fc0f8fef699642d88e27f2b

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: ${{ sha256 }}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - flit-core
  run:
    - python >=${{ python_min }}
    - numpy >=1.0
    - spglib >=1.9.4
    - scipy

tests:
  - python:
      imports:
        - seekpath
        - seekpath.brillouinzone
        - seekpath.hpkot
      pip_check: false
      python_version: ${{ python_min }}
about:
  license: MIT
  license_file: LICENSE.txt
  summary: A module to obtain and visualize k-vector coefficients and obtain band paths in the Brillouin zone of crystal structures.
  homepage: http://github.com/giovannipizzi/seekpath

extra:
  recipe-maintainers:
    - t-reents
    - npavlovikj
    - jan-janssen
