travis:
  secure:
    BINSTAR_TOKEN: QQTKMc+nYW/J3X1c2AxMCHoYciZIMXcJ8S+FiH2cZ6HDjqh3jPQ+KIUUB1dL6CvaKw9F5V6y8ZItH9HOFRasgcWVUBWjnb3vP5miOJEvh5Mu7yoWP29LQ+3wxlWg/HVVTTeuDucIhlQNTCjyXOdGZeQBko5bP6l5weVp5/yYUjFPLwoF/N8vPExjxJ399BWosQgeqL8HRry/BhJmoEFbl2YzGX18xfM1IaYqt+JHiQDq8tqW89plP31G3p6twwNBDjd7o7vlGk+Pcux9gyRT8cZHgbqnFSKd8oWg5N7LOBOFjwbeZ676Bd0MSX9ShI+Wzs616pltkwfYjBOfQneCsvYjaeQb+Xu0hWfyok/4C3FPwbdBx/D62DtkbjOrWNrK8tS15lEf7XZ42SPi/7udDVHBZCbmiBWvaF/QqLNKH2DTeFZZdY/b13JeQsaNamwCUu+l5N+IE+074A1BiHPCfJDYmy0KsrhkoY8ty4u6BCr/14IhxdEpswMOiR8/usSTQDIDEzkB1imrlZI6T3cdjxL0ZCyUlEseZ4Ir3s0WKBtoWwh6MvlhzTx/XcT6TrBYSMyid08xQ6dZuETNSmm0y6Ih+/iMlfHHTdb1NF7gVdOoYcwIt3u5P8hBKMObIi4cCshdQj95fM/4K5V2kdFYCS/vfPSZaveGeQgl/fNe/e4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
